---
driver:
  name: ec2
  aws_ssh_key_id: ec2_amazon_apache
  security_group_ids: ["sg-d6f0729d"]
  region: us-east-1
  availability_zone: us-east-1b
  require_chef_omnibus: true
  subnet_id: subnet-2f7c1365
  iam_profile_name: EC2_Roles
  instance_type: m3.medium
  associate_public_ip: true
  interface: dns

transport:
  ssh_key: /Users/jose/.ssh/ec2_amazon_apache.pem
  connection_timeout: 10
  connection_retries: 5
  username: ec2-user

platforms:
  - name: amazon
    driver:
      image_id: ami-afd15ed0
      block_device_mappings:
        - device_name: /dev/sdb
          ebs:
            volume_type: gp2
            volume_size: 8
            delete_on_termination: true

suites:
  - name: default
    run_list:
      - recipe[elk_cookbook::default]
    attributes:
